// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAojKp3blFQqL3AX7f13-Qm3wBI-TZtZ6Y',
    appId: '1:1078514308551:android:25740d59738cfba69735e2',
    messagingSenderId: '1078514308551',
    projectId: 'skilllink-r1xyh',
    storageBucket: 'skilllink-r1xyh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8yGoJkvvaXV2jheT0aauIfYz2EKJJbKY',
    appId: '1:1078514308551:ios:71e0aaa63d6f03469735e2',
    messagingSenderId: '1078514308551',
    projectId: 'skilllink-r1xyh',
    storageBucket: 'skilllink-r1xyh.firebasestorage.app',
    iosBundleId: 'com.example.skillLink',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWNlYlp8e07cZGqM8WCGh5XxQF8Zbly0k',
    appId: '1:1078514308551:web:9b0394d498f5fe0f9735e2',
    messagingSenderId: '1078514308551',
    projectId: 'skilllink-r1xyh',
    authDomain: 'skilllink-r1xyh.firebaseapp.com',
    storageBucket: 'skilllink-r1xyh.firebasestorage.app',
  );

}